# Generated by Django 4.2 on 2023-08-05 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=40, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("admin", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=20)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="External",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KPI_Metric",
            fields=[
                (
                    "guid",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "target_quantitative",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("description", models.CharField(max_length=200)),
                ("Created_At", models.DateTimeField()),
                ("Updated_At", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Senior_Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reporting_Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KPI_Measure",
            fields=[
                (
                    "guid",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("operating_period", models.IntegerField()),
                ("stage", models.CharField(max_length=40)),
                ("BRAG_status", models.BooleanField(default=False)),
                ("comments", models.CharField(max_length=400)),
                ("reporting_lead_approve", models.BooleanField(default=False)),
                ("manager_approve", models.BooleanField(default=False)),
                ("senior_manager_approve", models.BooleanField(default=False)),
                ("external_supervisor_approve", models.BooleanField(default=False)),
                ("director_approve", models.BooleanField(default=False)),
                ("Created_At", models.DateTimeField()),
                ("Updated_At", models.DateTimeField()),
                (
                    "KPI",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpi.kpi_metric",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpi.director",
                    ),
                ),
                (
                    "external_supervisor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpi.external",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpi.manager",
                    ),
                ),
                (
                    "reporting_lead",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpi.reporting_lead",
                    ),
                ),
                (
                    "senior_manager",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpi.senior_manager",
                    ),
                ),
            ],
        ),
    ]
