# Generated by Django 4.2 on 2023-08-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi_measure",
            name="cycle_target_quantitative",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name="kpi_measure",
            name="ytd_quantitative",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
