# Generated by Django 4.2 on 2023-10-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi_metric",
            name="score",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
