# Generated by Django 4.2 on 2023-10-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0002_kpi_metric_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="kpi_metric",
            name="ytd_target",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
